enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
included-patches = "'Add splash animation' 'MaterialYou'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
module-prop-name = "Youtube-magisk"

[Music]
enabled = true
app-name = "YT-Music"
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"
module-prop-name = "YT-Music-magisk"

[Tiktok]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
excluded-patches = "'Custom branding name YouTube' 'Custom branding icon YouTube'"
included-patches = "'Add splash animation' 'Disable landscape mode' 'Enable music search'" 
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"

[Music-Extended]
enabled = false
app-name = "YT-Music"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
excluded-patches = "'Custom branding name YouTube Music' 'Custom branding icon YouTube Music'"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
arch = "both"

[Tiktok]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Twitter]
enabled = false
build-mode = "apk"
merge-integrations = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

[Twitch]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
